spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    name: sheblossoms

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes
  jpa:
    hibernate:
      ddl-auto: update